version: "3"

services:
  light:
    image: registy.shellmates.club/lights
    ports:
      - '5501:80'
    networks:
      light_network:
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M

networks:
  light_network:
  