version: '3'
services:
  database:
    build: ./bdd/
    environment:
      MYSQL_DATABASE: 'wargame'
      MYSQL_USER: 'shellmates'
      MYSQL_PASSWORD: 'My_Sup3r_Secr3t_P@$$word'
      MYSQL_ROOT_PASSWORD: 'F91a9Mh2nWkDwtsL4NctLDKCBvqK8ss5'
    expose:
      - '3306'
  web:
    build: ./www/
    ports:
     - "8080:80"
    volumes:
      - ./www/src:/var/www/html
    depends_on:
      - database
