version: "3"
services:
  sqli_baabyyyy_db:
    image: registry.shellmates.club/sqli_baabyyyy_db
    environment:
      MYSQL_DATABASE: "sqli_baby_omega"
      MYSQL_USER: "omega_coder"
      MYSQL_PASSWORD: "omega_coder_was_here_1337"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      sqli_baabyyyy_network:

  sqli_baabyyyy_web:
    image: registry.shellmates.club/sqli_baabyyyy_web
    ports:
      - "2202:80"
    networks:
      sqli_baabyyyy_network:

networks:
  sqli_baabyyyy_network:
